export const SCREEN_TITLE = "SCREEN_TITLE";
export const SCREEN_MAIN = "SCREEN_MAIN";
export const SCREEN_LOBBY = "SCREEN_LOBBY";
export const SCREEN_GAME_WAGER = "SCREEN_GAME_WAGER";
export const SCREEN_GAME_DECIDE = "SCREEN_GAME_DECIDE";
export const SCREEN_GAME_RESULT = "SCREEN_GAME_RESULT";
