import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    buttonText: {
        color: '#0A0943',
        fontWeight: 'bold',
        fontSize: 20,
    },
    button: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F8F8F8',
        height: 50,
        width: 300,
        position: 'absolute',
        bottom: 20,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#AC8D30',
    },
    ready: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F8F8F8',
        height: 50,
        width: 300,
        position: 'absolute',
        bottom: 20,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#9C9B9B',
    },
    opponentReady: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFB7B6',
        height: 50,
        width: 300,
        position: 'absolute',
        bottom: 20,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#AF4845',
    },
    waiting: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#92CD97',
        height: 50,
        width: 300,
        position: 'absolute',
        bottom: 20,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#378D36',
    },
    logo: {
        position: 'absolute',
        top: 40,
        height: 80,
        resizeMode: 'contain',
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#0A0943',
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#0A0943',
    },
    splitBig: {
        color: '#92CD97',
        fontWeight: 'bold',
        fontSize: 40,
    },
    stealBig: {
        color: '#FFB7B6',
        fontWeight: 'bold',
        fontSize: 40,
    },
    split: {
        color: '#92CD97',
        fontSize: 30,
    },
    steal: {
        color: '#FFB7B6',
        fontSize: 30,
    },
    subtext: {
        color: '#F8F8F8',
        fontSize: 25,
    },
    input: {
        color: '#0A0943',
        fontWeight: 'bold',
        fontSize: 30,
    },
    field: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F8F8F8',
        height: 50,
        width: 300,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#AC8D30',
    },
    verticalSpacing: {
        height: 50,
    },
    horizontalSpacing: {
        width: 25,
    },
    money: {
        color: '#F8F8F8',
        fontWeight: 'bold',
        fontSize: 40,
    },
    title: {
        color: '#92CD97',
        fontWeight: 'bold',
        fontSize: 40,
    },
    spacing: {
        height: 50,
    },
    left: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F8F8F8',
        height: 50,
        width: 125,
        right: 25,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#AC8D30',
    },
    right: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F8F8F8',
        height: 50,
        width: 125,
        left: 25,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#AC8D30',
    },
    room: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    result: {
        color: '#F8F8F8',
        fontWeight: 'bold',
        fontSize: 35,
    }
});
